[project]
name = "environment-scripts"
version = "0.1.0"
description = "A collection of convinient environment scripts with an automatically updated README"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.5",
]
